name: Run Python Script Continuously

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Max execution time (~6 hours)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt || true  # Ignore errors if no requirements.txt

      - name: Run Python script continuously
        run: |
          cat > script.py << 'EOF'
          import time

          while True:
              print("Script is running...")
              time.sleep(600)  # Wait 10 minutes before next execution
          EOF
          
          python main.py
